### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [alexxi0213/xmapper#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary xmapper -w /tmp/ext xmapper==1.0.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting xmapper==1.0.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/83d/8bbdebe372edd/xmapper-1.0.0.tar.gz (7.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-srgkk29b/xmapper/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-srgkk29b/xmapper/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-srgkk29b/xmapper/pip-egg-info
         cwd: /tmp/pip-wheel-srgkk29b/xmapper/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-srgkk29b/xmapper/setup.py", line 17, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by alexxi0213** [comment]
Thank you for your feedback, you can try version `1.0.1` it should work:
```
➜  ext pip3 wheel --no-binary xmapper -w /tmp/ext xmapper==1.0.1
Collecting xmapper==1.0.1
  Downloading https://files.pythonhosted.org/packages/66/85/661abd6483fc367f7c802adc81d681a47a57fe121a559890bfabddad542f/xmapper-1.0.1.tar.gz
Collecting lxml==4.4.2 (from xmapper==1.0.1)
  Using cached https://files.pythonhosted.org/packages/50/a4/fb2c4441028bc81d3b50f970a8471ac5b34e64fcc85d5dc304691b0c41ff/lxml-4.4.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
  Saved ./lxml-4.4.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting PyYAML==5.2 (from xmapper==1.0.1)
  Using cached https://files.pythonhosted.org/packages/8d/c9/e5be955a117a1ac548cdd31e37e8fd7b02ce987f9655f5c7563c656d5dcb/PyYAML-5.2.tar.gz
Collecting untangle==1.1.1 (from xmapper==1.0.1)
  Saved ./untangle-1.1.1-cp36-none-any.whl
Skipping lxml, due to already being wheel.
Skipping untangle, due to already being wheel.
Building wheels for collected packages: xmapper, PyYAML
  Running setup.py bdist_wheel for xmapper ... done
  Stored in directory: /private/tmp/ext
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /private/tmp/ext
Successfully built xmapper PyYAML
```

**Comment by thatch** [comment]
Verified fixed!
